//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swissdec.SUA.OrganizationAuthentication
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
    public partial class OrganizationAuthenticationFaultType
    {
        
        private FaultContextType faultContextField;
        
        private FaultStateType faultStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FaultContextType FaultContext
        {
            get
            {
                return this.faultContextField;
            }
            set
            {
                this.faultContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FaultStateType FaultState
        {
            get
            {
                return this.faultStateField;
            }
            set
            {
                this.faultStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
    public partial class FaultContextType
    {
        
        private UserAgentType userAgentField;
        
        private string organizationNameField;
        
        private System.DateTime transmissionDateField;
        
        private string responseIDField;
        
        private string requestIDField;
        
        private EmptyType testCaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UserAgentType UserAgent
        {
            get
            {
                return this.userAgentField;
            }
            set
            {
                this.userAgentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrganizationName
        {
            get
            {
                return this.organizationNameField;
            }
            set
            {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TransmissionDate
        {
            get
            {
                return this.transmissionDateField;
            }
            set
            {
                this.transmissionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public EmptyType TestCase
        {
            get
            {
                return this.testCaseField;
            }
            set
            {
                this.testCaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public partial class UserAgentType
    {
        
        private string producerField;
        
        private string nameField;
        
        private string versionField;
        
        private decimal standardVersionField;
        
        private string certificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Producer
        {
            get
            {
                return this.producerField;
            }
            set
            {
                this.producerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal StandardVersion
        {
            get
            {
                return this.standardVersionField;
            }
            set
            {
                this.standardVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public partial class NotificationType
    {
        
        private QualityLevelType qualityLevelField;
        
        private string descriptionCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QualityLevelType QualityLevel
        {
            get
            {
                return this.qualityLevelField;
            }
            set
            {
                this.qualityLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string DescriptionCode
        {
            get
            {
                return this.descriptionCodeField;
            }
            set
            {
                this.descriptionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public enum QualityLevelType
    {
        
        /// <remarks/>
        Validity,
        
        /// <remarks/>
        Plausibility,
        
        /// <remarks/>
        Acceptance,
        
        /// <remarks/>
        Comment,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public partial class FaultStateType
    {
        
        private FaultCodeType codeField;
        
        private NotificationType[] errorField;
        
        private NotificationType[] warningField;
        
        private NotificationType[] infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FaultCodeType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Notification", IsNullable=false)]
        public NotificationType[] Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Notification", IsNullable=false)]
        public NotificationType[] Warning
        {
            get
            {
                return this.warningField;
            }
            set
            {
                this.warningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Notification", IsNullable=false)]
        public NotificationType[] Info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public enum FaultCodeType
    {
        
        /// <remarks/>
        NOT_accepted,
        
        /// <remarks/>
        NOT_plausible,
        
        /// <remarks/>
        NOT_valid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
    public partial class CredentialsType
    {
        
        private string keyField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
    public partial class RegisterOrganisationConsumerType
    {
        
        private ResponseContextType addresseeContextField;
        
        private CredentialsType credentialsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseContextType AddresseeContext
        {
            get
            {
                return this.addresseeContextField;
            }
            set
            {
                this.addresseeContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CredentialsType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
    public partial class ResponseContextType
    {
        
        private UserAgentType userAgentField;
        
        private string institutionNameField;
        
        private System.DateTime transmissionDateField;
        
        private string responseIDField;
        
        private string requestIDField;
        
        private EmptyType testCaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UserAgentType UserAgent
        {
            get
            {
                return this.userAgentField;
            }
            set
            {
                this.userAgentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InstitutionName
        {
            get
            {
                return this.institutionNameField;
            }
            set
            {
                this.institutionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TransmissionDate
        {
            get
            {
                return this.transmissionDateField;
            }
            set
            {
                this.transmissionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public EmptyType TestCase
        {
            get
            {
                return this.testCaseField;
            }
            set
            {
                this.testCaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public partial class EmptyType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public partial class AddressType
    {
        
        private string complementaryLineField;
        
        private string streetField;
        
        private string postboxField;
        
        private string localityField;
        
        private string zIPCodeField;
        
        private string cityField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ComplementaryLine
        {
            get
            {
                return this.complementaryLineField;
            }
            set
            {
                this.complementaryLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Postbox
        {
            get
            {
                return this.postboxField;
            }
            set
            {
                this.postboxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZIP-Code", Order=4)]
        public string ZIPCode
        {
            get
            {
                return this.zIPCodeField;
            }
            set
            {
                this.zIPCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public partial class CompanyOwnerType
    {
        
        private string firstnameField;
        
        private string lastnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public partial class DelegateType
    {
        
        private CompanyNameType nameField;
        
        private CompanyOwnerType ownerField;
        
        private AddressType addressField;
        
        private string uIDBFSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CompanyNameType Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CompanyOwnerType Owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AddressType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UID-BFS", DataType="NMTOKEN", Order=3)]
        public string UIDBFS
        {
            get
            {
                return this.uIDBFSField;
            }
            set
            {
                this.uIDBFSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public partial class CompanyNameType
    {
        
        private string hRRCNameField;
        
        private string[] complementaryLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HR-RC-Name", Order=0)]
        public string HRRCName
        {
            get
            {
                return this.hRRCNameField;
            }
            set
            {
                this.hRRCNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComplementaryLine", Order=1)]
        public string[] ComplementaryLine
        {
            get
            {
                return this.complementaryLineField;
            }
            set
            {
                this.complementaryLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class AuthorizedForCompanyType
    {
        
        private DelegateType companyField;
        
        private ContactPersonType contactPersonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DelegateType Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ContactPersonType ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class ContactPersonType
    {
        
        private string nameField;
        
        private string departmentField;
        
        private string emailAddressField;
        
        private string phoneNumberField;
        
        private string mobilePhoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MobilePhoneNumber
        {
            get
            {
                return this.mobilePhoneNumberField;
            }
            set
            {
                this.mobilePhoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class GenericInstitutionIdentificationType
    {
        
        private string institutionIDField;
        
        private string institutionCompanyNameField;
        
        private string customerIdentityField;
        
        private string contractIdentityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InstitutionID
        {
            get
            {
                return this.institutionIDField;
            }
            set
            {
                this.institutionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InstitutionCompanyName
        {
            get
            {
                return this.institutionCompanyNameField;
            }
            set
            {
                this.institutionCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerIdentity
        {
            get
            {
                return this.customerIdentityField;
            }
            set
            {
                this.customerIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContractIdentity
        {
            get
            {
                return this.contractIdentityField;
            }
            set
            {
                this.contractIdentityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class OtherCustomerIdentificationType
    {
        
        private string swissdecStandardField;
        
        private string swissdecDomainNameField;
        
        private GenericInstitutionIdentificationType swissdecInstitutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SwissdecStandard
        {
            get
            {
                return this.swissdecStandardField;
            }
            set
            {
                this.swissdecStandardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SwissdecDomainName
        {
            get
            {
                return this.swissdecDomainNameField;
            }
            set
            {
                this.swissdecDomainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public GenericInstitutionIdentificationType SwissdecInstitution
        {
            get
            {
                return this.swissdecInstitutionField;
            }
            set
            {
                this.swissdecInstitutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class StatisticIdentificationType
    {
        
        private string customerIdentityField;
        
        private string customerIdentity2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerIdentity
        {
            get
            {
                return this.customerIdentityField;
            }
            set
            {
                this.customerIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerIdentity2
        {
            get
            {
                return this.customerIdentity2Field;
            }
            set
            {
                this.customerIdentity2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class TaxAtSourceCustomerIdentificationBaseType
    {
        
        private CantonAddressType cantonIDField;
        
        private string customerIdentityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CantonAddressType CantonID
        {
            get
            {
                return this.cantonIDField;
            }
            set
            {
                this.cantonIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerIdentity
        {
            get
            {
                return this.customerIdentityField;
            }
            set
            {
                this.customerIdentityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public enum CantonAddressType
    {
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AI,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BL,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        JU,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NW,
        
        /// <remarks/>
        OW,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TI,
        
        /// <remarks/>
        UR,
        
        /// <remarks/>
        VD,
        
        /// <remarks/>
        VS,
        
        /// <remarks/>
        ZG,
        
        /// <remarks/>
        ZH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="FAK-CAF-CustomerIdentificationBaseType", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class FAKCAFCustomerIdentificationBaseType
    {
        
        private string fAKCAFBranchNumberField;
        
        private string fAKCAFCustomerNumberField;
        
        private string fAKCAFSubNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FAK-CAF-BranchNumber", Order=0)]
        public string FAKCAFBranchNumber
        {
            get
            {
                return this.fAKCAFBranchNumberField;
            }
            set
            {
                this.fAKCAFBranchNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FAK-CAF-CustomerNumber", Order=1)]
        public string FAKCAFCustomerNumber
        {
            get
            {
                return this.fAKCAFCustomerNumberField;
            }
            set
            {
                this.fAKCAFCustomerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FAK-CAF-SubNumber", Order=2)]
        public string FAKCAFSubNumber
        {
            get
            {
                return this.fAKCAFSubNumberField;
            }
            set
            {
                this.fAKCAFSubNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class GenericCustomerIdentificationMultiType
    {
        
        private string insuranceIDField;
        
        private string insuranceCompanyNameField;
        
        private string customerIdentityField;
        
        private string contractIdentityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InsuranceID
        {
            get
            {
                return this.insuranceIDField;
            }
            set
            {
                this.insuranceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InsuranceCompanyName
        {
            get
            {
                return this.insuranceCompanyNameField;
            }
            set
            {
                this.insuranceCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerIdentity
        {
            get
            {
                return this.customerIdentityField;
            }
            set
            {
                this.customerIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContractIdentity
        {
            get
            {
                return this.contractIdentityField;
            }
            set
            {
                this.contractIdentityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="AHV-AVS-CustomerIdentificationBaseType", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class AHVAVSCustomerIdentificationBaseType
    {
        
        private string aKCCBranchNumberField;
        
        private string aKCCCustomerNumberField;
        
        private string aKCCSubNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AK-CC-BranchNumber", DataType="NMTOKEN", Order=0)]
        public string AKCCBranchNumber
        {
            get
            {
                return this.aKCCBranchNumberField;
            }
            set
            {
                this.aKCCBranchNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AK-CC-CustomerNumber", Order=1)]
        public string AKCCCustomerNumber
        {
            get
            {
                return this.aKCCCustomerNumberField;
            }
            set
            {
                this.aKCCCustomerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AK-CC-SubNumber", Order=2)]
        public string AKCCSubNumber
        {
            get
            {
                return this.aKCCSubNumberField;
            }
            set
            {
                this.aKCCSubNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class InstitutionsType
    {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AHV-AVS", typeof(AHVAVSCustomerIdentificationBaseType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BVG-LPP", typeof(GenericCustomerIdentificationMultiType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FAK-CAF", typeof(FAKCAFCustomerIdentificationBaseType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KTG-AMC", typeof(GenericCustomerIdentificationMultiType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KU-AC", typeof(GenericCustomerIdentificationMultiType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Other", typeof(OtherCustomerIdentificationType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Statistic", typeof(StatisticIdentificationType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Tax", typeof(TaxAtSourceCustomerIdentificationBaseType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TaxAtSource", typeof(TaxAtSourceCustomerIdentificationBaseType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UVG-LAA", typeof(GenericCustomerIdentificationMultiType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UVGZ-LAAC", typeof(GenericCustomerIdentificationMultiType), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AHV-AVS")]
        AHVAVS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BVG-LPP")]
        BVGLPP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("FAK-CAF")]
        FAKCAF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KTG-AMC")]
        KTGAMC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KU-AC")]
        KUAC,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        Statistic,
        
        /// <remarks/>
        Tax,
        
        /// <remarks/>
        TaxAtSource,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UVG-LAA")]
        UVGLAA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UVGZ-LAAC")]
        UVGZLAAC,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationRegistrationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class OrganizationRegistrationBaseType
    {
        
        private InstitutionsType institutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InstitutionsType Institution
        {
            get
            {
                return this.institutionField;
            }
            set
            {
                this.institutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class OrganizationRegistrationType : OrganizationRegistrationBaseType
    {
        
        private string companyUIDBFSField;
        
        private CompanyNameType companyNameField;
        
        private ContactPersonType companyContactPersonField;
        
        private AuthorizedForCompanyType authorizedForField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompanyUID-BFS", DataType="NMTOKEN", Order=0)]
        public string CompanyUIDBFS
        {
            get
            {
                return this.companyUIDBFSField;
            }
            set
            {
                this.companyUIDBFSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CompanyNameType CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ContactPersonType CompanyContactPerson
        {
            get
            {
                return this.companyContactPersonField;
            }
            set
            {
                this.companyContactPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AuthorizedForCompanyType AuthorizedFor
        {
            get
            {
                return this.authorizedForField;
            }
            set
            {
                this.authorizedForField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
    public partial class RequestContextType
    {
        
        private UserAgentType userAgentField;
        
        private CompanyNameType companyNameField;
        
        private System.DateTime transmissionDateField;
        
        private string requestIDField;
        
        private LanguageCodeType languageCodeField;
        
        private EmptyType testCaseField;
        
        private string monitoringIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UserAgentType UserAgent
        {
            get
            {
                return this.userAgentField;
            }
            set
            {
                this.userAgentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CompanyNameType CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TransmissionDate
        {
            get
            {
                return this.transmissionDateField;
            }
            set
            {
                this.transmissionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public LanguageCodeType LanguageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public EmptyType TestCase
        {
            get
            {
                return this.testCaseField;
            }
            set
            {
                this.testCaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MonitoringID
        {
            get
            {
                return this.monitoringIDField;
            }
            set
            {
                this.monitoringIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
    public enum LanguageCodeType
    {
        
        /// <remarks/>
        de,
        
        /// <remarks/>
        fr,
        
        /// <remarks/>
        it,
        
        /// <remarks/>
        en,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationService", ConfigurationName="Swissdec.SUA.OrganizationAuthentication.OrganizationAuthenticationPort")]
    public interface OrganizationAuthenticationPort
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrganizationRegistrationBaseType))]
        System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.PingResponse> PingAsync(Swissdec.SUA.OrganizationAuthentication.PingRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrganizationRegistrationBaseType))]
        System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.CheckInteroperabilityResponse> CheckInteroperabilityAsync(Swissdec.SUA.OrganizationAuthentication.CheckInteroperabilityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Swissdec.SUA.OrganizationAuthentication.OrganizationAuthenticationFaultType), Action="", Name="OrganizationAuthenticationFault", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrganizationRegistrationBaseType))]
        System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.RegisterOrganizationResponse> RegisterOrganizationAsync(Swissdec.SUA.OrganizationAuthentication.RegisterOrganizationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Swissdec.SUA.OrganizationAuthentication.OrganizationAuthenticationFaultType), Action="", Name="OrganizationAuthenticationFault", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrganizationRegistrationBaseType))]
        System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.GetResultFromRegisterOrganizationResponse> GetResultFromRegisterOrganizationAsync(Swissdec.SUA.OrganizationAuthentication.GetResultFromRegisterOrganizationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Swissdec.SUA.OrganizationAuthentication.OrganizationAuthenticationFaultType), Action="", Name="OrganizationAuthenticationFault", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrganizationRegistrationBaseType))]
        System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.SignCertificateResponse> SignCertificateAsync(Swissdec.SUA.OrganizationAuthentication.SignCertificateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class PingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public Swissdec.SUA.OrganizationAuthentication.UserAgentType UserAgent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public System.DateTime SystemDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public string MonitoringID;
        
        public PingRequest()
        {
        }
        
        public PingRequest(Swissdec.SUA.OrganizationAuthentication.UserAgentType UserAgent, System.DateTime SystemDateTime, string MonitoringID)
        {
            this.UserAgent = UserAgent;
            this.SystemDateTime = SystemDateTime;
            this.MonitoringID = MonitoringID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class PingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public Swissdec.SUA.OrganizationAuthentication.UserAgentType UserAgent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public System.DateTime SystemDateTime;
        
        public PingResponse()
        {
        }
        
        public PingResponse(Swissdec.SUA.OrganizationAuthentication.UserAgentType UserAgent, System.DateTime SystemDateTime)
        {
            this.UserAgent = UserAgent;
            this.SystemDateTime = SystemDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInteroperability", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class CheckInteroperabilityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public Swissdec.SUA.OrganizationAuthentication.UserAgentType UserAgent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public string UmlautString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public decimal FirstOperand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public decimal SecondOperand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public System.DateTime SystemDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public string MonitoringID;
        
        public CheckInteroperabilityRequest()
        {
        }
        
        public CheckInteroperabilityRequest(Swissdec.SUA.OrganizationAuthentication.UserAgentType UserAgent, string UmlautString, decimal FirstOperand, decimal SecondOperand, System.DateTime SystemDateTime, string MonitoringID)
        {
            this.UserAgent = UserAgent;
            this.UmlautString = UmlautString;
            this.FirstOperand = FirstOperand;
            this.SecondOperand = SecondOperand;
            this.SystemDateTime = SystemDateTime;
            this.MonitoringID = MonitoringID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInteroperabilityResponse", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class CheckInteroperabilityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public Swissdec.SUA.OrganizationAuthentication.UserAgentType UserAgent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public bool UmlautStringIsCorrect;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public bool FirstOperandIsCorrect;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public string UmlautString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public decimal AdditionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public decimal SubtractionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/common/20200220/Common")]
        public System.DateTime SystemDateTime;
        
        public CheckInteroperabilityResponse()
        {
        }
        
        public CheckInteroperabilityResponse(Swissdec.SUA.OrganizationAuthentication.UserAgentType UserAgent, bool UmlautStringIsCorrect, bool FirstOperandIsCorrect, string UmlautString, decimal AdditionResult, decimal SubtractionResult, System.DateTime SystemDateTime)
        {
            this.UserAgent = UserAgent;
            this.UmlautStringIsCorrect = UmlautStringIsCorrect;
            this.FirstOperandIsCorrect = FirstOperandIsCorrect;
            this.UmlautString = UmlautString;
            this.AdditionResult = AdditionResult;
            this.SubtractionResult = SubtractionResult;
            this.SystemDateTime = SystemDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterOrganization", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class RegisterOrganizationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.RequestContextType RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.OrganizationRegistrationType OrganizationRegistration;
        
        public RegisterOrganizationRequest()
        {
        }
        
        public RegisterOrganizationRequest(Swissdec.SUA.OrganizationAuthentication.RequestContextType RequestContext, Swissdec.SUA.OrganizationAuthentication.OrganizationRegistrationType OrganizationRegistration)
        {
            this.RequestContext = RequestContext;
            this.OrganizationRegistration = OrganizationRegistration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterOrganizationResponse", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class RegisterOrganizationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.ResponseContextType ResponseContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("CertificateRequest-ID", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public string CertificateRequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.RegisterOrganisationConsumerType RegisterOrganisationConsumer;
        
        public RegisterOrganizationResponse()
        {
        }
        
        public RegisterOrganizationResponse(Swissdec.SUA.OrganizationAuthentication.ResponseContextType ResponseContext, string CertificateRequestID, Swissdec.SUA.OrganizationAuthentication.RegisterOrganisationConsumerType RegisterOrganisationConsumer)
        {
            this.ResponseContext = ResponseContext;
            this.CertificateRequestID = CertificateRequestID;
            this.RegisterOrganisationConsumer = RegisterOrganisationConsumer;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
    public partial class ResultType
    {
        
        private ResponseContextType addresseeContextField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseContextType AddresseeContext
        {
            get
            {
                return this.addresseeContextField;
            }
            set
            {
                this.addresseeContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Processing", typeof(ProcessingType), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Success", typeof(RegistrationQuittanceType), Order=1)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
    public partial class ProcessingType
    {
        
        private System.DateTime expectedAvailabilityField;
        
        private bool expectedAvailabilityFieldSpecified;
        
        private NotificationType[] commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime ExpectedAvailability
        {
            get
            {
                return this.expectedAvailabilityField;
            }
            set
            {
                this.expectedAvailabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpectedAvailabilitySpecified
        {
            get
            {
                return this.expectedAvailabilityFieldSpecified;
            }
            set
            {
                this.expectedAvailabilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Notification", Namespace="http://www.swissdec.ch/schema/common/20200220/Common", IsNullable=false)]
        public NotificationType[] Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class RegistrationQuittanceType
    {
        
        private RegistrationQuittanceTypeX509Subject x509SubjectField;
        
        private string companyUIDBFSField;
        
        private string authorizedForUIDBFSField;
        
        private NotificationType[] commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RegistrationQuittanceTypeX509Subject X509Subject
        {
            get
            {
                return this.x509SubjectField;
            }
            set
            {
                this.x509SubjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompanyUID-BFS", DataType="NMTOKEN", Order=1)]
        public string CompanyUIDBFS
        {
            get
            {
                return this.companyUIDBFSField;
            }
            set
            {
                this.companyUIDBFSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AuthorizedForUID-BFS", DataType="NMTOKEN", Order=2)]
        public string AuthorizedForUIDBFS
        {
            get
            {
                return this.authorizedForUIDBFSField;
            }
            set
            {
                this.authorizedForUIDBFSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Notification", Namespace="http://www.swissdec.ch/schema/common/20200220/Common", IsNullable=false)]
        public NotificationType[] Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class RegistrationQuittanceTypeX509Subject
    {
        
        private string commonNameField;
        
        private string organizationNameField;
        
        private string localityNameField;
        
        private string stateOrProvinceNameField;
        
        private string countryNameField;
        
        private string businessCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CommonName
        {
            get
            {
                return this.commonNameField;
            }
            set
            {
                this.commonNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrganizationName
        {
            get
            {
                return this.organizationNameField;
            }
            set
            {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LocalityName
        {
            get
            {
                return this.localityNameField;
            }
            set
            {
                this.localityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StateOrProvinceName
        {
            get
            {
                return this.stateOrProvinceNameField;
            }
            set
            {
                this.stateOrProvinceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CountryName
        {
            get
            {
                return this.countryNameField;
            }
            set
            {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BusinessCategory
        {
            get
            {
                return this.businessCategoryField;
            }
            set
            {
                this.businessCategoryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResultFromOrganizationRegistration", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class GetResultFromRegisterOrganizationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.RequestContextType RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("CertificateRequest-ID", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public string CertificateRequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.InstitutionsType Institution;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.CredentialsType Credentials;
        
        public GetResultFromRegisterOrganizationRequest()
        {
        }
        
        public GetResultFromRegisterOrganizationRequest(Swissdec.SUA.OrganizationAuthentication.RequestContextType RequestContext, string CertificateRequestID, Swissdec.SUA.OrganizationAuthentication.InstitutionsType Institution, Swissdec.SUA.OrganizationAuthentication.CredentialsType Credentials)
        {
            this.RequestContext = RequestContext;
            this.CertificateRequestID = CertificateRequestID;
            this.Institution = Institution;
            this.Credentials = Credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResultFromOrganizationRegistrationResponse", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class GetResultFromRegisterOrganizationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.ResponseContextType ResponseContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("CertificateRequest-ID", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public string CertificateRequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.ResultType Result;
        
        public GetResultFromRegisterOrganizationResponse()
        {
        }
        
        public GetResultFromRegisterOrganizationResponse(Swissdec.SUA.OrganizationAuthentication.ResponseContextType ResponseContext, string CertificateRequestID, Swissdec.SUA.OrganizationAuthentication.ResultType Result)
        {
            this.ResponseContext = ResponseContext;
            this.CertificateRequestID = CertificateRequestID;
            this.Result = Result;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class CertificateSignRequestType : CertificateSignRequestBaseType
    {
        
        private string oneTimePasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OneTimePassword
        {
            get
            {
                return this.oneTimePasswordField;
            }
            set
            {
                this.oneTimePasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CertificateSignRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class CertificateSignRequestBaseType
    {
        
        private byte[] pEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] PEM
        {
            get
            {
                return this.pEMField;
            }
            set
            {
                this.pEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthentication")]
    public partial class CertificateSignResponseType
    {
        
        private string subjectDNField;
        
        private string issuerDNField;
        
        private System.DateTime notBeforeField;
        
        private System.DateTime notAfterField;
        
        private byte[] pEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubjectDN
        {
            get
            {
                return this.subjectDNField;
            }
            set
            {
                this.subjectDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IssuerDN
        {
            get
            {
                return this.issuerDNField;
            }
            set
            {
                this.issuerDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime NotBefore
        {
            get
            {
                return this.notBeforeField;
            }
            set
            {
                this.notBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime NotAfter
        {
            get
            {
                return this.notAfterField;
            }
            set
            {
                this.notAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] PEM
        {
            get
            {
                return this.pEMField;
            }
            set
            {
                this.pEMField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignCertificate", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class SignCertificateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.RequestContextType RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("CertificateRequest-ID", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public string CertificateRequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.CertificateSignRequestType CertificateSignRequest;
        
        public SignCertificateRequest()
        {
        }
        
        public SignCertificateRequest(Swissdec.SUA.OrganizationAuthentication.RequestContextType RequestContext, string CertificateRequestID, Swissdec.SUA.OrganizationAuthentication.CertificateSignRequestType CertificateSignRequest)
        {
            this.RequestContext = RequestContext;
            this.CertificateRequestID = CertificateRequestID;
            this.CertificateSignRequest = CertificateSignRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignCertificateResponse", WrapperNamespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationServiceTypes", IsWrapped=true)]
    public partial class SignCertificateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.ResponseContextType ResponseContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("CertificateRequest-ID", Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public string CertificateRequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public Swissdec.SUA.OrganizationAuthentication.CertificateSignResponseType Certificate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.swissdec.ch/schema/oa/20230301/OrganizationAuthenticationContainer")]
        public string RevokePassword;
        
        public SignCertificateResponse()
        {
        }
        
        public SignCertificateResponse(Swissdec.SUA.OrganizationAuthentication.ResponseContextType ResponseContext, string CertificateRequestID, Swissdec.SUA.OrganizationAuthentication.CertificateSignResponseType Certificate, string RevokePassword)
        {
            this.ResponseContext = ResponseContext;
            this.CertificateRequestID = CertificateRequestID;
            this.Certificate = Certificate;
            this.RevokePassword = RevokePassword;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface OrganizationAuthenticationPortChannel : Swissdec.SUA.OrganizationAuthentication.OrganizationAuthenticationPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class OrganizationAuthenticationPortClient : System.ServiceModel.ClientBase<Swissdec.SUA.OrganizationAuthentication.OrganizationAuthenticationPort>, Swissdec.SUA.OrganizationAuthentication.OrganizationAuthenticationPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrganizationAuthenticationPortClient() : 
                base(OrganizationAuthenticationPortClient.GetDefaultBinding(), OrganizationAuthenticationPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OrganizationAuthentication.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrganizationAuthenticationPortClient(EndpointConfiguration endpointConfiguration) : 
                base(OrganizationAuthenticationPortClient.GetBindingForEndpoint(endpointConfiguration), OrganizationAuthenticationPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrganizationAuthenticationPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrganizationAuthenticationPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrganizationAuthenticationPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrganizationAuthenticationPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrganizationAuthenticationPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.PingResponse> PingAsync(Swissdec.SUA.OrganizationAuthentication.PingRequest request)
        {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.CheckInteroperabilityResponse> CheckInteroperabilityAsync(Swissdec.SUA.OrganizationAuthentication.CheckInteroperabilityRequest request)
        {
            return base.Channel.CheckInteroperabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.RegisterOrganizationResponse> RegisterOrganizationAsync(Swissdec.SUA.OrganizationAuthentication.RegisterOrganizationRequest request)
        {
            return base.Channel.RegisterOrganizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.GetResultFromRegisterOrganizationResponse> GetResultFromRegisterOrganizationAsync(Swissdec.SUA.OrganizationAuthentication.GetResultFromRegisterOrganizationRequest request)
        {
            return base.Channel.GetResultFromRegisterOrganizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Swissdec.SUA.OrganizationAuthentication.SignCertificateResponse> SignCertificateAsync(Swissdec.SUA.OrganizationAuthentication.SignCertificateRequest request)
        {
            return base.Channel.SignCertificateAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrganizationAuthentication))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrganizationAuthentication))
            {
                return new System.ServiceModel.EndpointAddress("http://tst.itserve.ch/services/OrganizationAuthentication");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OrganizationAuthenticationPortClient.GetBindingForEndpoint(EndpointConfiguration.OrganizationAuthentication);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OrganizationAuthenticationPortClient.GetEndpointAddress(EndpointConfiguration.OrganizationAuthentication);
        }
        
        public enum EndpointConfiguration
        {
            
            OrganizationAuthentication,
        }
    }
}
